# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modifications made by Leo Palmer, 2025:
# - Use Go 1.24.
# - Upgrade some actions.
# - Remove the use of CodeClimate.
# - Remove simplebar OAuth testing.
# - Use GoReleaser for releases.

name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Check out code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Install go cover
      run: go install golang.org/x/tools/cmd/cover@latest

    - name: Fix apt-get state
      run: sudo apt-get update

    - name: Install apt packages
      run: sudo apt-get install libasound2-dev jq

    - name: Run tests
      env:
        CI: true
      run: ./test.sh

    - name: Set up GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest

    - name: Delete old autorelease
      run: |
        gh release delete autorelease --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new tag
      run: |
        git tag autorelease
        git push origin autorelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goreleaser release --clean